# configs/tasks/pick_place.yaml
task: pick_place
criteria:
  reach:
    distance_threshold: 0.1
  grasp:
    finger_close_threshold: 0.1
  lift:
    min_height_delta: 0.1
  place:
    target_position: [0.1, -0.1, 0.1]
    distance_threshold: 0.10
subtask_weights:
  reach: 0.1
  grasp: 0.1
  lift: 0.1
  place: 0.1
success_threshold: 0.1

#set up your own parameter in this section, it's just example
